### ISSUE TITLE
Update major requirements

### ISSUE THREAD

**Issue by skiadas** [sdp-resources/MajorPlanner#28]
Need to assign points.

- Does this include adding and removing a requirement? Is there actually an "edit requirement" option that alters an existing requirement?
- Do we need to split this?

**Comment by CelesteHackmann** [comment]
Do we want to edit existing majors or add a new major for students that have yet to declare? If we simply update the major requirements, that may affect those who have already declared their major and thus it may mess up their schedule and say it is no longer satisfying the major.

**Comment by Hayesb20** [comment]
i would say for this issue it would be okay to update the requirements to majors already selected and in another part of the program, write it in such a way that it will notify the creator if a change has made an issue with their current plan or something.

**Comment by Hayesb20** [comment]
i also wonder if this couldn't be combined with major creator because it will use a lot of the same functionality. i would imaging that to change a major requirements we would need to change a majors fields to include or to not include a tag or a value. ( but if it cannot be combined i would give it a 1)

**Comment by skiadas** [comment]
Closing in  favor of #34 and #35
